bam_files:
    Pooled_PigDropSeq_SpinalCordControl1: Pooled_PigDropSeq_SpinalCordControl1.Read_1.fastq
    Pooled_PigDropSeq_DRGControl1: Pooled_PigDropSeq_DRGControl1.Read_1.fastq
    Pooled_PigDropSeq_SpinalCordIR1: Pooled_PigDropSeq_SpinalCordIR1.Read_1.fastq
    Pooled_PigDropSeq_DRGIR1: Pooled_PigDropSeq_DRGIR1.Read_1.fastq
